# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCase1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_case1(self):
    self.driver.get("https://www.avianca.com/es/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, "#languageListTriggerId_53 .dropdown_trigger_value").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#languageListTriggerId_53 .dropdown_trigger_value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.ID, "optionId_languageListOptionsLisId_670").click()
    self.driver.find_element(By.CSS_SELECTOR, "#languageListTriggerId_12 .dropdown_trigger_value").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "#languageListTriggerId_12 .dropdown_trigger_value")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#optionId_languageListOptionsLisId_862 > .button_label").click()
    self.driver.find_element(By.CSS_SELECTOR, "#languageListTriggerId_9 .dropdown_trigger_value").click()
    self.driver.find_element(By.CSS_SELECTOR, "#optionId_languageListOptionsLisId_912 > .button_label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".content-wrap").click()
  
