# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFooter():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_footer(self):
    self.driver.get("https://www.avianca.com/es/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c30-5:nth-child(1) > .ng-tns-c30-5 > .link-label").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c12-6:nth-child(2) > .ng-tns-c12-6 > .link-label").click()
    self.vars["win123"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win123"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".btn-twitter > svg").click()
    self.vars["win8585"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win8585"])
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.CSS_SELECTOR, ".ng-tns-c12-8:nth-child(1) > .ng-tns-c12-8 > .link-label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown_trigger_value").click()
    self.driver.find_element(By.CSS_SELECTOR, "#optionId_languageListOptionsLisId_20 > .button_label").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dropdown_trigger_value").click()
    self.driver.find_element(By.CSS_SELECTOR, "#optionId_languageListOptionsLisId_251 > .button_label").click()
  
